name: CI

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main

jobs:
  podman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build
        id: build
        uses: samarthj/arch-pkgbuild-action@v0.1
        with:
          pkgbuild_root: podman-git

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ${{ steps.build.outputs.podman-git }}
            ${{ steps.build.outputs.podman-docker-git }}
          if-no-files-found: error
