name: Build packages

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package:
          [
            'buildah-git',
            'conmon-git',
            'containers-common-git',
            'crun-git',
            'podman-dnsname-git',
            'podman-git',
            'skopeo-git',
            'slirp4netns-git',
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build
        id: build
        uses: samarthj/arch-pkgbuild-action@v1
        with:
          pkgbuild_root: ${{ matrix.package }}
          aur_username: Sam
          aur_email: dev@samarthj.com
          aur_ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          dry_run: false
        env:
          GOPATH: /home/builder/.local/share/go
          GOCACHE: /home/builder/.cache/go
      - name: Delete tag ${{ matrix.package }}
        uses: cb80/delrel@latest
        with:
          tag: ${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release tag ${{ matrix.package }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ matrix.package }}
          name: ${{ steps.build.outputs.ver0 }}
          body: ${{ steps.build.outputs.ver0 }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: '*.tar.zst'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@master
        with:
          rebase: true
          author_name: Sam
          author_email: dev@samarthj.com
          message: 'ci(github-actions): updpkg: ${{ steps.build.outputs.ver0 }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
