name: Executor

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: choice
        options:
          - pyinstaller
      dry_run:
        required: false
        default: true
        type: boolean
      install_optdepends:
        required: false
        default: false
        type: boolean
      use_pypi_prerelease_version:
        required: false
        default: false
        type: boolean
      use_pypi_release_version:
        required: false
        default: false
        type: boolean
      is_python_pkg:
        required: false
        default: false
        type: boolean
      use_git_release_version:
        required: false
        default: false
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  arbitrary:
    if:  ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/worker.yml
    with:
      package: ${{ inputs.package }}
      dry_run: ${{ inputs.dry_run }}
      use_pypi_prerelease_version: ${{ inputs.use_pypi_prerelease_version }}
      use_pypi_release_version: ${{ inputs.use_pypi_release_version }}
      use_git_release_version: ${{ inputs.use_git_release_version }}
      is_python_pkg: ${{ inputs.is_python_pkg }}
    secrets:
      aur-ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      gpg-passphrase: ${{ secrets.PASSPHRASE }}
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
  pyinstaller:
    if:  ${{ github.event_name == 'schedule' }}
    strategy:
      matrix:
        package:
          - pyinstaller
          - pyinstaller-hooks-contrib
    uses: ./.github/workflows/worker.yml
    with:
      package: ${{ matrix.package }}
      dry_run: false
      use_pypi_release_version: true
      is_python_pkg: true
      pytest_addopts: --durations=50 --dist=load --timeout=120 --timeout-method=thread -v -rsxXfE --doctest-glob=
    secrets:
      aur-ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      gpg-passphrase: ${{ secrets.PASSPHRASE }}
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}