name: Git Push

on:
  workflow_call:
    inputs:
      pkg-version:
        required: true
        type: string

jobs:
  git-push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git config
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Sam"
          git config --global user.email dev@samarthj.com
          git config --global user.signkey dev@samarthj.com
          git config --global commit.gpgsign true
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Rebase and Push
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git status
          [ -z "$(git status --porcelain --untracked-files=no)" ] && exit 0
          git commit --message "ci(github-actions): :package: updpkg: ${{ inputs.pkg-version }}"
          git fetch origin main
          git pull --rebase origin main
          git push
