name: Worker

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      dry_run:
        required: false
        default: true
        type: boolean
      install_optdepends:
        required: false
        default: false
        type: boolean
      use_pypi_prerelease_version:
        required: false
        default: false
        type: boolean
      use_pypi_release_version:
        required: false
        default: false
        type: boolean
      use_git_release_version:
        required: false
        default: false
        type: boolean
      pytest_addopts:
        required: false
        default: ""
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.package }}
  cancel-in-progress: true

jobs:
  pkgbuild:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkg-name: ${{ inputs.package }}
      dry_run: ${{ inputs.dry_run }}
      install_optdepends: ${{ inputs.install_optdepends }}
      use_pypi_prerelease_version: ${{ inputs.use_pypi_prerelease_version }}
      use_pypi_release_version: ${{ inputs.use_pypi_release_version }}
      use_git_release_version: ${{ inputs.use_git_release_version }}
      is_python_pkg: ${{ inputs.is_python_pkg }}
      pytest_addopts: ${{ inputs.pytest_addopts }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      aur-ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

  git-push:
    uses: ./.github/workflows/git-push.yml
    needs:
      - pkgbuild
    with:
      pkg-name: ${{ inputs.package }}
      pkg-version: ${{ needs.pkgbuild.outputs.pkg-version }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.PASSPHRASE }}

  git-tag:
    uses: ./.github/workflows/git-push.yml
    needs:
      - git-push
    with:
      pkg-name: ${{ inputs.package }}
      pkg-version: ${{ needs.pkgbuild.outputs.pkg-version }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
