name: Worker

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      dry_run:
        required: false
        default: true
        type: boolean
      install_optdepends:
        required: false
        default: false
        type: boolean
      use_pypi_prerelease_version:
        required: false
        default: false
        type: boolean
      use_pypi_release_version:
        required: false
        default: false
        type: boolean
      use_git_release_version:
        required: false
        default: false
        type: boolean
      is_python_pkg:
        required: false
        default: false
        type: boolean
      pytest_addopts:
        required: false
        default: ""
        type: string
    secrets:
      aur-ssh-private-key:
        required: true
      github-token:
        required: true
      gpg-passphrase:
        required: true
      gpg-private-key:
        required: true

jobs:
  pkgbuild:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkg-name: ${{ inputs.package }}
      dry_run: ${{ inputs.dry_run }}
      install_optdepends: ${{ inputs.install_optdepends }}
      use_pypi_prerelease_version: ${{ inputs.use_pypi_prerelease_version }}
      use_pypi_release_version: ${{ inputs.use_pypi_release_version }}
      use_git_release_version: ${{ inputs.use_git_release_version }}
      is_python_pkg: ${{ inputs.is_python_pkg }}
      pytest_addopts: ${{ inputs.pytest_addopts }}
    secrets:
      github-token: ${{ secrets.github-token }}
      aur-ssh-private-key: ${{ secrets.aur-ssh-private-key }}

  git-push:
    uses: ./.github/workflows/git-push.yml
    needs:
      - pkgbuild
    with:
      pkg-name: ${{ inputs.package }}
      pkg-version: ${{ needs.pkgbuild.outputs.pkg-version }}
    secrets:
      github-token: ${{ secrets.github-token }}
      gpg-passphrase: ${{ secrets.gpg-passphrase }}
      gpg-private-key: ${{ secrets.gpg-private-key }}

  git-tag:
    uses: ./.github/workflows/git-tag.yml
    needs:
      - git-push
    with:
      pkg-name: ${{ inputs.package }}
      pkg-version: ${{ needs.pkgbuild.outputs.pkg-version }}
    secrets:
      github-token: ${{ secrets.github-token }}
